import DesignerContextProvider from "@/components/context/DesignerContext";
import Logo from "@/components/Logo";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Former",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <DesignerContextProvider>
            <ThemeProvider
              enableSystem
              disableTransitionOnChange
              attribute="class"
              defaultTheme="system">
              <nav className="flex justify-between items-center border-b border-border h-[60px] px-4 py-2">
                <Logo />
                <div className="flex items-center gap-4">
                  <ThemeSwitcher />
                  <UserButton afterSignOutUrl="/sign-in" />
                </div>
              </nav>
              {children}
              <Toaster />
            </ThemeProvider>
          </DesignerContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
